name = "IR 2"
author = "Sinbelisk"
version = "0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606be48897ae3276894b1234ca1153010ab35ae251b4f4b6c508fb73c68df611"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
