name = "IR 2"
author = "Sinbelisk"
version = "0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed0038b74f650ae24b135aed22dc253b6ae8005f6f86684857598ebc46aa9cc3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
