name = "IR 2"
author = "Sinbelisk"
version = "0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "694e8dd21bc1591e19f966f39df644253abacf1b0358e971a0995a9b3c59ed8c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
