name = "IR 2"
author = "Sinbelisk"
version = "0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc2dfc73b24a9c601e3e9ae3bdc5b4635478717df34fa085e63af58bf2dcff03"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
